spring:
  security:
    filter.order: 10
  datasource:
    url: jdbc:h2:file:./planv_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true

logging.level:
  org.springframework: DEBUG
  org.hibernate.SQL: DEBUG

application.jwt:
  secret-key: helloworldhelloworldhelloworldhelloworldhelloworldhelloworld
  token-expiration-days: 1
